# Generated by Django 5.1.7 on 2025-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
