# Generated by Django 5.1.7 on 2025-05-11 18:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_email_token_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
