# Generated by Django 5.1.7 on 2025-05-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_profile_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_token_used',
            field=models.BooleanField(default=False),
        ),
    ]
