# Generated by Django 5.1.7 on 2025-05-14 17:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_email_token_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
