# Generated by Django 5.1.7 on 2025-05-19 16:25

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default=accounts.models.generate_uuid_str, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
